# Huấn luyện CNN–LSTM song song để so sánh công bằng

Notebook này retrain ba mô hình độc lập trên `kaggle`, `csic` và `obfu_http` để so sánh topology với CNN–LSTM tuần tự hiện tại.

- Đọc đúng các file train/validation/test đã lưu bởi notebook tuần tự; không tự chia lại dữ liệu.
- Dùng lại đúng tokenizer char-level của model tuần tự cho từng dataset.
- Giữ nguyên HTTP envelope, seed 42, batch size 128, class weight, optimizer, early stopping và threshold 0.5.
- Đọc `MAX_LEN` và số epoch riêng từ metadata tuần tự: Kaggle/CSIC dùng 1024 và 50 epoch; OBFU dùng 768 và 30 epoch.
- OBFU được đánh giá trên test chính và ba test split unseen.
- Hai nhánh CNN và LSTM nhận cùng embedding rồi concatenate trước tầng phân loại.
- Chỉ topology và số tham số phát sinh từ topology được phép khác nhau.

Artifact cũ không được tái sử dụng mặc định. Hãy chạy lại toàn bộ notebook để tạo kết quả song song mới.


## 1. Thiết lập môi trường và cấu hình


In [4]:
from pathlib import Path
import gc
import json
import os
import pickle
import random
import sys
import time

START_DIR = Path.cwd().resolve()
if (START_DIR / "preprocessing" / "preprocess_data.py").exists():
    PROJECT_ROOT = START_DIR
elif START_DIR.name == "cnn_lstm_parallel" and (START_DIR.parent / "preprocessing" / "preprocess_data.py").exists():
    PROJECT_ROOT = START_DIR.parent
else:
    raise FileNotFoundError("Hãy chạy notebook từ repo root hoặc thư mục cnn_lstm_parallel.")

NOTEBOOK_DIR = PROJECT_ROOT / "cnn_lstm_parallel"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(NOTEBOOK_DIR)

import numpy as np
import pandas as pd
import tensorflow as tf
from IPython.display import display
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import (
    Concatenate, Conv1D, Dense, Dropout, Embedding,
    GlobalMaxPooling1D, Input, LSTM, MaxPooling1D,
)
from tensorflow.keras.metrics import AUC, Precision, Recall
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

from preprocessing import preprocess_data as prep

SEED = 42
EMBEDDING_DIM = 64
BATCH_SIZE = 128
DECISION_THRESHOLD = 0.50
THRESHOLD_STRATEGY = "fixed"
EARLY_STOPPING_MIN_DELTA = 1e-4
DATASET_NAMES = ("kaggle", "csic", "obfu_http")

# Nguồn chuẩn duy nhất cho split và tokenizer của phép so sánh topology.
REFERENCE_ARTIFACT_ROOT = (
    PROJECT_ROOT / "cnn_lstm" / "artifacts_cnn_lstm_by_dataset"
)
REFERENCE_SPLIT_ROOT = REFERENCE_ARTIFACT_ROOT / "processed_data_by_dataset"
REFERENCE_MODEL_ROOT = REFERENCE_ARTIFACT_ROOT / "by_dataset"
REFERENCE_METADATA_PATH = REFERENCE_ARTIFACT_ROOT / "preprocessing_metadata.json"

# Giữ đường dẫn này để cell so sánh trong CNN_LSTM.ipynb đọc được artifact mới.
ARTIFACT_ROOT = NOTEBOOK_DIR / "artifacts"

required_paths = [
    PROJECT_ROOT / "preprocessing" / "preprocess_data.py",
    REFERENCE_METADATA_PATH,
]
for dataset_name in DATASET_NAMES:
    required_paths.extend([
        REFERENCE_SPLIT_ROOT / dataset_name / "train.csv",
        REFERENCE_SPLIT_ROOT / dataset_name / "val.csv",
        REFERENCE_SPLIT_ROOT / dataset_name / "test.csv",
        REFERENCE_MODEL_ROOT / dataset_name / "tokenizer.pkl",
        REFERENCE_MODEL_ROOT / dataset_name / "metadata_and_results.json",
    ])
missing_paths = [path for path in required_paths if not path.exists()]
if missing_paths:
    attempted = "\n".join(f"- {path}" for path in missing_paths)
    raise FileNotFoundError(
        "Thiếu artifact tuần tự dùng làm chuẩn so sánh:\n" + attempted
    )

random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)
ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Reference split root:", REFERENCE_SPLIT_ROOT)
print("Reference tokenizer root:", REFERENCE_MODEL_ROOT)
print("Parallel artifact root:", ARTIFACT_ROOT)
print("TensorFlow:", tf.__version__)
print("GPU available:", bool(tf.config.list_physical_devices("GPU")))


Project root: C:\Users\admin\Desktop\obfuscated-web-attack-detection
Reference split root: C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm\artifacts_cnn_lstm_by_dataset\processed_data_by_dataset
Reference tokenizer root: C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm\artifacts_cnn_lstm_by_dataset\by_dataset
Parallel artifact root: C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm_parallel\artifacts
TensorFlow: 2.21.0
GPU available: False


## 2. Nạp đúng split của mô hình tuần tự

Notebook không gọi splitter lần nữa. Các file `train.csv`, `val.csv` và `test.csv` được đọc trực tiếp từ `cnn_lstm/artifacts_cnn_lstm_by_dataset/processed_data_by_dataset/`.

Điều này đảm bảo hai topology nhìn thấy đúng cùng sample, cùng nhãn, cùng HTTP envelope và cùng thứ tự dữ liệu. Notebook sẽ dừng ngay nếu metadata không phải `random_stratified_row` hoặc payload không có unified HTTP envelope.


In [5]:
with REFERENCE_METADATA_PATH.open("r", encoding="utf-8") as file:
    preprocessing_metadata = json.load(file)

policy = preprocessing_metadata["preprocessing_policy"]
if policy.get("split_protocol") != "random_stratified_row":
    raise ValueError(
        "Split chuẩn không dùng random_stratified_row: "
        f"{policy.get('split_protocol')!r}"
    )

dataset_splits = {}
for dataset_name in DATASET_NAMES:
    source_dir = REFERENCE_SPLIT_ROOT / dataset_name
    splits = {}
    split_names = list(
        preprocessing_metadata["datasets"][dataset_name]["splits"]
    )
    for split_name in split_names:
        frame = pd.read_csv(source_dir / f"{split_name}.csv")
        frame["payload"] = frame["payload"].fillna("").astype(str)
        frame["label"] = frame["label"].astype(np.int32)
        if frame.empty:
            raise ValueError(f"Split rỗng: {dataset_name}/{split_name}")
        if not frame["payload"].str.startswith("[METHOD]").all():
            raise ValueError(
                f"Split {dataset_name}/{split_name} không dùng unified HTTP envelope."
            )
        expected_rows = int(
            preprocessing_metadata["datasets"][dataset_name]["splits"][split_name]["rows"]
        )
        if len(frame) != expected_rows:
            raise ValueError(
                f"Sai số dòng {dataset_name}/{split_name}: "
                f"expected={expected_rows}, actual={len(frame)}"
            )
        splits[split_name] = frame
    dataset_splits[dataset_name] = splits

# Đọc cấu hình component trực tiếp từ metadata tuần tự thay vì lặp hard-code.
TOPOLOGY_FIELDS = (
    "max_len",
    "epochs_requested",
    "embedding_dim",
    "cnn_filters",
    "cnn_kernel_sizes",
    "cnn_pool_sizes",
    "lstm_units",
    "lstm_return_sequences",
    "lstm_pooling",
    "dense_units",
    "dropout",
    "learning_rate",
)
EXPECTED_COMMON_TOPOLOGY = {
    "embedding_dim": EMBEDDING_DIM,
    "cnn_filters": [128, 128],
    "cnn_kernel_sizes": [3, 5],
    "cnn_pool_sizes": [4, 4],
    "lstm_units": 128,
    "lstm_return_sequences": True,
    "lstm_pooling": "GlobalMaxPooling1D",
    "dense_units": 64,
    "dropout": 0.3,
    "learning_rate": 1e-3,
}
EXPECTED_DATASET_TRAINING = {
    "kaggle": {"max_len": 1024, "epochs_requested": 50},
    "csic": {"max_len": 1024, "epochs_requested": 50},
    "obfu_http": {"max_len": 768, "epochs_requested": 30},
}

topology_contracts = {}
for dataset_name in DATASET_NAMES:
    metadata_path = REFERENCE_MODEL_ROOT / dataset_name / "metadata_and_results.json"
    with metadata_path.open("r", encoding="utf-8") as file:
        sequential_metadata = json.load(file)
    sequential_model = sequential_metadata["model"]
    contract = {field: sequential_model.get(field) for field in TOPOLOGY_FIELDS}
    mismatches = {
        field: (contract[field], expected)
        for field, expected in {**EXPECTED_COMMON_TOPOLOGY, **EXPECTED_DATASET_TRAINING[dataset_name]}.items()
        if contract[field] != expected
    }
    if mismatches:
        details = ", ".join(
            f"{field}: sequential={actual!r}, expected={expected!r}"
            for field, (actual, expected) in mismatches.items()
        )
        raise ValueError(
            f"Topology tuần tự {dataset_name.upper()} không khớp contract: {details}"
        )
    topology_contracts[dataset_name] = contract

print("Đã nạp chính xác split của model tuần tự:")
for dataset_name, splits in dataset_splits.items():
    print(
        f"- {dataset_name.upper()}: "
        + " | ".join(f"{name}={len(frame):,}" for name, frame in splits.items())
    )

print("Topology component đã đồng bộ từ metadata tuần tự:")
for dataset_name, contract in topology_contracts.items():
    print(f"- {dataset_name.upper()}:", contract)


Đã nạp chính xác split của model tuần tự:
- KAGGLE: train=109,197 | val=12,133 | test=30,333
- CSIC: train=43,966 | val=4,886 | test=12,213
- OBFU_HTTP: train=63,700 | val=13,649 | test=13,649 | test_unseen_technique=13,000 | test_unseen_seed=13,000 | test_unseen_both=13,000
Topology component đã đồng bộ từ metadata tuần tự:
- KAGGLE: {'max_len': 1024, 'epochs_requested': 50, 'embedding_dim': 64, 'cnn_filters': [128, 128], 'cnn_kernel_sizes': [3, 5], 'cnn_pool_sizes': [4, 4], 'lstm_units': 128, 'lstm_return_sequences': True, 'lstm_pooling': 'GlobalMaxPooling1D', 'dense_units': 64, 'dropout': 0.3, 'learning_rate': 0.001}
- CSIC: {'max_len': 1024, 'epochs_requested': 50, 'embedding_dim': 64, 'cnn_filters': [128, 128], 'cnn_kernel_sizes': [3, 5], 'cnn_pool_sizes': [4, 4], 'lstm_units': 128, 'lstm_return_sequences': True, 'lstm_pooling': 'GlobalMaxPooling1D', 'dense_units': 64, 'dropout': 0.3, 'learning_rate': 0.001}
- OBFU_HTTP: {'max_len': 768, 'epochs_requested': 30, 'embedding_dim': 64

In [6]:
audit_rows = []
for dataset_name, splits in dataset_splits.items():
    dataset_max_len = int(topology_contracts[dataset_name]["max_len"])
    for split_name, frame in splits.items():
        label_counts = frame["label"].value_counts().to_dict()
        lengths = frame["payload"].str.len()
        audit_rows.append({
            "dataset": dataset_name,
            "split": split_name,
            "rows": len(frame),
            "normal": int(label_counts.get(0, 0)),
            "attack": int(label_counts.get(1, 0)),
            "attack_rate": float(frame["label"].mean()),
            "p95_length": float(lengths.quantile(0.95)),
            "over_max_len": int((lengths > dataset_max_len).sum()),
        })

dataset_audit = pd.DataFrame(audit_rows)
display(dataset_audit)
print("Tiền xử lý được thực hiện bởi preprocessing/preprocess_data.py.")


,dataset,split,rows,normal,attack,attack_rate,p95_length,over_max_len
0,kaggle,train,109197,38647,70550,0.646080,1006.00,4382
1,kaggle,val,12133,4294,7839,0.646089,1007.00,495
2,kaggle,test,30333,10736,19597,0.646062,1003.00,1195
3,csic,train,43966,25920,18046,0.410454,437.00,0
4,csic,val,4886,2880,2006,0.410561,437.00,0
5,csic,test,12213,7200,5013,0.410464,437.00,0
6,obfu_http,train,63700,31850,31850,0.500000,567.00,72
7,obfu_http,val,13649,6825,6824,0.499963,562.60,14
8,obfu_http,test,13649,6825,6824,0.499963,564.00,19
9,obfu_http,test_unseen_technique,13000,6500,6500,0.500000,578.00,31


Tiền xử lý được thực hiện bởi preprocessing/preprocess_data.py.


## 3. Dùng chung tokenizer và vectorization

Mỗi model song song dùng trực tiếp `tokenizer.pkl` của model tuần tự tương ứng. Notebook đồng thời fit một tokenizer kiểm tra trên train split và yêu cầu `word_index` phải giống hoàn toàn trước khi bắt đầu train.

Vectorization tạo cùng ma trận `N × 1024`, `padding="post"` và `truncating="post"` như pipeline tuần tự. Cách gọi `model.fit` cũng dùng array, `batch_size=128`, `shuffle=True` và `class_weight` giống nhau.


In [7]:
def vectorize(tokenizer, payloads, max_len):
    sequences = tokenizer.texts_to_sequences(payloads)
    return pad_sequences(
        sequences,
        maxlen=max_len,
        padding="post",
        truncating="post",
        dtype="int32",
    )


def prepare_dataset_for_training(dataset_name, splits):
    tokenizer_path = REFERENCE_MODEL_ROOT / dataset_name / "tokenizer.pkl"
    with tokenizer_path.open("rb") as file:
        tokenizer = pickle.load(file)

    # Kiểm tra tokenizer tham chiếu đúng là tokenizer fit trên train hiện tại.
    audit_tokenizer = Tokenizer(
        char_level=True,
        lower=False,
        filters="",
        oov_token="<OOV>",
    )
    audit_tokenizer.fit_on_texts(splits["train"]["payload"])
    if audit_tokenizer.word_index != tokenizer.word_index:
        raise ValueError(
            f"Tokenizer tuần tự của {dataset_name} không khớp train split hiện tại."
        )

    y_train = splits["train"]["label"].to_numpy(dtype=np.int32)
    classes = np.unique(y_train)
    if set(classes.tolist()) != {0, 1}:
        raise ValueError(
            f"Train split phải có đủ nhãn 0 và 1, nhận được: {classes.tolist()}"
        )

    weights = compute_class_weight(
        class_weight="balanced", classes=classes, y=y_train
    )
    class_weight = {
        int(label): float(weight) for label, weight in zip(classes, weights)
    }
    return tokenizer, len(tokenizer.word_index) + 1, class_weight


## 4. Topology CNN và LSTM song song

Các hyperparameter component được đọc trực tiếp từ metadata CNN–LSTM tuần tự. CNN branch và LSTM branch dùng cùng embedding; chỉ phép nối giữa hai block thay đổi:

```text
Tuần tự : Embedding → CNN block → LSTM block → Dense
Song song: Embedding → [CNN block ∥ LSTM block] → Concatenate → Dense
```

GlobalMaxPooling ở cuối mỗi nhánh song song chỉ dùng để đưa hai tensor về vector trước khi concatenate và không có tham số trainable.


In [8]:
def build_parallel_cnn_lstm(dataset_name, vocab_size):
    contract = topology_contracts[dataset_name]
    max_len = int(contract["max_len"])
    embedding_dim = int(contract["embedding_dim"])
    cnn_filters = [int(value) for value in contract["cnn_filters"]]
    cnn_kernels = [int(value) for value in contract["cnn_kernel_sizes"]]
    cnn_pools = [int(value) for value in contract["cnn_pool_sizes"]]
    lstm_units = int(contract["lstm_units"])
    dense_units = int(contract["dense_units"])

    inputs = Input(shape=(max_len,), dtype="int32", name="payload_tokens")
    embedded = Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        name="char_embedding",
    )(inputs)

    cnn = Conv1D(
        cnn_filters[0], cnn_kernels[0], padding="same",
        activation="relu", name="cnn_conv_k3",
    )(embedded)
    cnn = MaxPooling1D(pool_size=cnn_pools[0], name="cnn_pool_1")(cnn)
    cnn = Conv1D(
        cnn_filters[1], cnn_kernels[1], padding="same",
        activation="relu", name="cnn_conv_k5",
    )(cnn)
    cnn = MaxPooling1D(pool_size=cnn_pools[1], name="cnn_pool_2")(cnn)
    cnn_vector = GlobalMaxPooling1D(name="cnn_global_max_pool")(cnn)

    lstm_sequence = LSTM(
        lstm_units,
        return_sequences=bool(contract["lstm_return_sequences"]),
        name="lstm_context_sequence",
    )(embedded)
    if contract["lstm_pooling"] != "GlobalMaxPooling1D":
        raise ValueError(
            f"LSTM pooling không được hỗ trợ: {contract['lstm_pooling']!r}"
        )
    lstm_vector = GlobalMaxPooling1D(name="lstm_global_max_pool")(
        lstm_sequence
    )

    merged = Concatenate(name="parallel_feature_fusion")([
        cnn_vector, lstm_vector
    ])
    dense = Dense(
        dense_units, activation="relu", name="dense_classifier"
    )(merged)
    dense = Dropout(float(contract["dropout"]), name="dropout")(dense)
    outputs = Dense(
        1, activation="sigmoid", name="attack_probability"
    )(dense)

    model = Model(inputs, outputs, name=f"Parallel_CNN_LSTM_{dataset_name}")
    model.compile(
        optimizer=Adam(learning_rate=float(contract["learning_rate"])),
        loss="binary_crossentropy",
        metrics=[
            "accuracy",
            AUC(name="auc"),
            Precision(name="precision"),
            Recall(name="recall"),
        ],
    )
    return model


## 5. Huấn luyện, đánh giá và lưu artifact

Mỗi dataset được ghi vào thư mục riêng dưới `cnn_lstm_parallel/artifacts/`. Artifact cũ của chính dataset sẽ bị model/checkpoint mới ghi đè khi retrain.

Checkpoint và early stopping giống model tuần tự: theo `val_loss`, `mode="min"`, `min_delta=1e-4`, `patience=3`, `restore_best_weights=True`. Model tốt nhất được reload trước khi đánh giá validation/test ở threshold cố định 0.5.


In [9]:
def portable_path(path):
    resolved = Path(path).resolve()
    try:
        return resolved.relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return str(resolved)


def evaluate_split(model, tokenizer, frame, split_name, max_len):
    features = vectorize(tokenizer, frame["payload"], max_len)
    probabilities = model.predict(
        features, batch_size=BATCH_SIZE, verbose=1
    ).ravel()
    labels = frame["label"].to_numpy(dtype=np.int32)
    predictions = (probabilities >= DECISION_THRESHOLD).astype(np.int32)
    matrix = confusion_matrix(labels, predictions, labels=[0, 1])
    report = classification_report(
        labels,
        predictions,
        labels=[0, 1],
        target_names=["Normal (0)", "Attack (1)"],
        output_dict=True,
        zero_division=0,
    )
    result = {
        "rows": int(len(frame)),
        "accuracy": float(accuracy_score(labels, predictions)),
        "auc_roc": (
            float(roc_auc_score(labels, probabilities))
            if len(np.unique(labels)) > 1 else None
        ),
        "false_positives": int(matrix[0, 1]),
        "false_negatives": int(matrix[1, 0]),
        "confusion_matrix": matrix.tolist(),
        "classification_report": report,
        "decision_threshold": DECISION_THRESHOLD,
    }
    print(f"\n=== {split_name.upper()} ===")
    print(classification_report(
        labels,
        predictions,
        labels=[0, 1],
        target_names=["Normal (0)", "Attack (1)"],
        digits=4,
        zero_division=0,
    ))
    print("Confusion matrix:\n", matrix)
    print("AUC-ROC:", result["auc_roc"])
    del features, probabilities
    return result


def train_one_dataset(dataset_name, splits):
    print("\n" + "=" * 80)
    print(f"TRAIN DATASET: {dataset_name.upper()}")
    print("=" * 80)
    tf.keras.backend.clear_session()
    tf.keras.utils.set_random_seed(SEED)

    tokenizer, vocab_size, class_weight = prepare_dataset_for_training(
        dataset_name, splits
    )
    topology_contract = topology_contracts[dataset_name]
    max_len = int(topology_contract["max_len"])
    epochs_requested = int(topology_contract["epochs_requested"])
    artifact_dir = ARTIFACT_ROOT / dataset_name
    artifact_dir.mkdir(parents=True, exist_ok=True)

    best_model_path = artifact_dir / "best_parallel_cnn_lstm.keras"
    last_model_path = artifact_dir / "last_parallel_cnn_lstm.keras"
    tokenizer_path = artifact_dir / "tokenizer.pkl"
    history_path = artifact_dir / "training_history.csv"
    results_path = artifact_dir / "metadata_and_results.json"

    # File này thuộc pipeline cũ; preprocessing hiện được nhúng trong metadata.
    legacy_config_path = artifact_dir / "preprocessing_config.json"
    if legacy_config_path.exists():
        legacy_config_path.unlink()

    X_train = vectorize(tokenizer, splits["train"]["payload"], max_len)
    X_val = vectorize(tokenizer, splits["val"]["payload"], max_len)
    y_train = splits["train"]["label"].to_numpy(dtype=np.int32)
    y_val = splits["val"]["label"].to_numpy(dtype=np.int32)

    model = build_parallel_cnn_lstm(dataset_name, vocab_size)
    model.summary()
    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            mode="min",
            min_delta=EARLY_STOPPING_MIN_DELTA,
            patience=3,
            restore_best_weights=True,
            verbose=1,
        ),
        ModelCheckpoint(
            filepath=str(best_model_path),
            monitor="val_loss",
            mode="min",
            save_best_only=True,
            verbose=1,
        ),
    ]

    started = time.perf_counter()
    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        batch_size=BATCH_SIZE,
        epochs=epochs_requested,
        callbacks=callbacks,
        class_weight=class_weight,
        shuffle=True,
        verbose=1,
    )
    training_seconds = time.perf_counter() - started
    model.save(last_model_path)
    with tokenizer_path.open("wb") as file:
        pickle.dump(tokenizer, file)
    pd.DataFrame(history.history).to_csv(
        history_path, index=False, encoding="utf-8"
    )

    del X_train, X_val, y_train, y_val
    gc.collect()

    best_model = tf.keras.models.load_model(best_model_path)
    evaluations = {
        "validation": evaluate_split(
            best_model,
            tokenizer,
            splits["val"],
            f"{dataset_name} validation",
            max_len,
        )
    }
    for split_name in sorted(name for name in splits if name.startswith("test")):
        evaluations[split_name] = evaluate_split(
            best_model,
            tokenizer,
            splits[split_name],
            f"{dataset_name} {split_name}",
            max_len,
        )

    preprocessing_config = {
        "dataset": dataset_name,
        "seed": SEED,
        "preprocessing_source": portable_path(REFERENCE_METADATA_PATH),
        "shared_split_source": portable_path(REFERENCE_SPLIT_ROOT / dataset_name),
        "shared_tokenizer_source": portable_path(
            REFERENCE_MODEL_ROOT / dataset_name / "tokenizer.pkl"
        ),
        "split_target": {"train": 0.72, "validation": 0.08, "test": 0.20},
        "split_protocol": "random_stratified_row",
        "group_column": "split_group",
        "url_decode": False,
        "html_unescape": False,
        "lowercase": False,
        "whitespace_normalization_only": True,
        "input_representation": "unified_http_envelope",
        "tokenizer_fit_split": "train",
        "vocab_size": int(vocab_size),
        "max_len": max_len,
        "padding": "post",
        "truncating": "post",
        "decision_threshold": DECISION_THRESHOLD,
        "threshold_strategy": THRESHOLD_STRATEGY,
        "class_weight": {
            str(key): float(value) for key, value in class_weight.items()
        },
        "splits": {
            name: prep.summarize(frame) for name, frame in splits.items()
        },
    }

    result = {
        "dataset": dataset_name,
        "train_source": dataset_name,
        "artifact_dir": portable_path(artifact_dir),
        "preprocessing": preprocessing_config,
        "model": {
            "name": best_model.name,
            "parameter_count": int(best_model.count_params()),
            "topology": "Shared Embedding -> [CNN branch -> GlobalMaxPool || LSTM(return_sequences=True) -> GlobalMaxPool] -> Concatenate -> Dense -> Sigmoid",
            "architecture_note": "Controlled topology comparison against sequential CNN-LSTM using identical saved splits and tokenizer.",
            "max_len": max_len,
            "vocab_size": int(vocab_size),
            "embedding_dim": int(topology_contract["embedding_dim"]),
            "cnn_filters": list(topology_contract["cnn_filters"]),
            "cnn_kernel_sizes": list(topology_contract["cnn_kernel_sizes"]),
            "cnn_pool_sizes": list(topology_contract["cnn_pool_sizes"]),
            "lstm_units": int(topology_contract["lstm_units"]),
            "lstm_return_sequences": bool(topology_contract["lstm_return_sequences"]),
            "lstm_pooling": topology_contract["lstm_pooling"],
            "dense_units": int(topology_contract["dense_units"]),
            "dropout": float(topology_contract["dropout"]),
            "learning_rate": float(topology_contract["learning_rate"]),
            "batch_size": BATCH_SIZE,
            "epochs_requested": epochs_requested,
            "epochs_ran": int(len(history.history["loss"])),
            "early_stopping_monitor": "val_loss",
            "early_stopping_mode": "min",
            "early_stopping_min_delta": EARLY_STOPPING_MIN_DELTA,
            "early_stopping_patience": 3,
            "decision_threshold": DECISION_THRESHOLD,
            "threshold_strategy": THRESHOLD_STRATEGY,
            "artifacts": {
                "best_model": portable_path(best_model_path),
                "last_model": portable_path(last_model_path),
                "tokenizer": portable_path(tokenizer_path),
                "training_history": portable_path(history_path),
            },
        },
        "training_seconds": float(training_seconds),
        "training_history": {
            key: [float(value) for value in values]
            for key, values in history.history.items()
        },
        "evaluation": evaluations,
    }
    with results_path.open("w", encoding="utf-8") as file:
        json.dump(result, file, ensure_ascii=False, indent=2)

    del model, best_model, history
    gc.collect()
    tf.keras.backend.clear_session()
    print("Đã lưu kết quả:", results_path)
    return result


## 6. Chọn dataset và retrain

Mặc định notebook retrain lần lượt Kaggle, CSIC rồi OBFU_HTTP. Nếu phiên Kaggle bị ngắt sau một dataset, chỉ giữ các dataset đã hoàn thành bằng `REUSE_COMPLETED_DATASETS=True` và đặt `DATASETS_TO_TRAIN` thành danh sách phần còn lại. Contract của artifact cũ sẽ được kiểm tra trước khi tái sử dụng.


In [10]:
DATASETS_TO_TRAIN = ["kaggle", "csic", "obfu_http"]
REUSE_COMPLETED_DATASETS = False

DATASETS_TO_TRAIN = [
    name.strip()
    for item in DATASETS_TO_TRAIN
    for name in str(item).split(",")
    if name.strip()
]
unknown_datasets = set(DATASETS_TO_TRAIN) - set(DATASET_NAMES)
if unknown_datasets:
    raise ValueError(f"Dataset không hợp lệ: {sorted(unknown_datasets)}")


def validate_reusable_result(dataset_name, result):
    preprocessing = result.get("preprocessing", {})
    model_config = result.get("model", {})
    expected = {
        "dataset": (result.get("dataset"), dataset_name),
        "seed": (preprocessing.get("seed"), SEED),
        "max_len": (
            preprocessing.get("max_len"),
            int(topology_contracts[dataset_name]["max_len"]),
        ),
        "epochs_requested": (
            model_config.get("epochs_requested"),
            int(topology_contracts[dataset_name]["epochs_requested"]),
        ),
        "input_representation": (
            preprocessing.get("input_representation"),
            "unified_http_envelope",
        ),
        "threshold_strategy": (
            model_config.get("threshold_strategy"), THRESHOLD_STRATEGY
        ),
        "decision_threshold": (
            model_config.get("decision_threshold"), DECISION_THRESHOLD
        ),
        "shared_split_source": (
            preprocessing.get("shared_split_source"),
            portable_path(REFERENCE_SPLIT_ROOT / dataset_name),
        ),
        "shared_tokenizer_source": (
            preprocessing.get("shared_tokenizer_source"),
            portable_path(REFERENCE_MODEL_ROOT / dataset_name / "tokenizer.pkl"),
        ),
        "early_stopping_min_delta": (
            model_config.get("early_stopping_min_delta"),
            EARLY_STOPPING_MIN_DELTA,
        ),
    }
    mismatches = {
        key: values for key, values in expected.items() if values[0] != values[1]
    }
    if mismatches:
        details = ", ".join(
            f"{key}: actual={actual!r}, expected={wanted!r}"
            for key, (actual, wanted) in mismatches.items()
        )
        raise ValueError(
            f"Artifact {dataset_name.upper()} không đủ điều kiện tái sử dụng: {details}"
        )


all_results = {}
all_results_path = ARTIFACT_ROOT / "all_dataset_results.json"

if REUSE_COMPLETED_DATASETS:
    for dataset_name in DATASET_NAMES:
        if dataset_name in DATASETS_TO_TRAIN:
            continue
        result_path = ARTIFACT_ROOT / dataset_name / "metadata_and_results.json"
        if not result_path.exists():
            raise FileNotFoundError(
                f"Không có artifact để tái sử dụng cho {dataset_name}: {result_path}"
            )
        with result_path.open("r", encoding="utf-8") as file:
            existing_result = json.load(file)
        validate_reusable_result(dataset_name, existing_result)
        all_results[dataset_name] = existing_result
        print(f"Tái sử dụng artifact hợp lệ: {dataset_name.upper()}")

for dataset_name in DATASETS_TO_TRAIN:
    all_results[dataset_name] = train_one_dataset(
        dataset_name, dataset_splits[dataset_name]
    )
    with all_results_path.open("w", encoding="utf-8") as file:
        json.dump(all_results, file, ensure_ascii=False, indent=2)

comparison_rows = []
for dataset_name in DATASET_NAMES:
    if dataset_name not in all_results:
        continue
    result = all_results[dataset_name]
    test = result["evaluation"]["test"]
    attack = test["classification_report"]["Attack (1)"]
    comparison_rows.append({
        "dataset": dataset_name,
        "test_rows": test["rows"],
        "threshold": DECISION_THRESHOLD,
        "accuracy": test["accuracy"],
        "auc_roc": test["auc_roc"],
        "attack_precision": attack["precision"],
        "attack_recall": attack["recall"],
        "attack_f1": attack["f1-score"],
        "false_positives": test["false_positives"],
        "false_negatives": test["false_negatives"],
        "parameters": result["model"]["parameter_count"],
        "epochs_ran": result["model"]["epochs_ran"],
        "training_seconds": result["training_seconds"],
    })

comparison = pd.DataFrame(comparison_rows)
comparison.to_csv(
    ARTIFACT_ROOT / "dataset_comparison.csv",
    index=False,
    encoding="utf-8",
)
display(comparison)
print("Đã train trong lần chạy này:", ", ".join(DATASETS_TO_TRAIN))
print("Đã lưu tổng hợp:", all_results_path)



TRAIN DATASET: KAGGLE



Model: "Parallel_CNN_LSTM_kaggle"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ payload_tokens      │ (None, 1024)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ char_embedding      │ (None, 1024, 64)  │     13,632 │ payload_tokens[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cnn_conv_k3         │ (None, 1024, 128) │     24,704 │ char_embedding[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cnn_pool_1          │ (None, 256, 128)  │          0 │ cnn_conv_k3[0][0] │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cnn_conv_k5         │ (None, 256, 128)  │     82,048 │ cnn_pool_1[0][0]  │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cnn_pool_2          │ (None, 64, 128)   │          0 │ cnn_conv_k5[0][0] │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_context_seque… │ (None, 1024, 128) │     98,816 │ char_embedding[0… │
│ (LSTM)              │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cnn_global_max_pool │ (None, 128)       │          0 │ cnn_pool_2[0][0]  │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_global_max_po… │ (None, 128)       │          0 │ lstm_context_seq… │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ parallel_feature_f… │ (None, 256)       │          0 │ cnn_global_max_p… │
│ (Concatenate)       │                   │            │ lstm_global_max_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_classifier    │ (None, 64)        │     16,448 │ parallel_feature… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 64)        │          0 │ dense_classifier… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attack_probability  │ (None, 1)         │         65 │ dropout[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 235,713 (920.75 KB)

 Trainable params: 235,713 (920.75 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
854/854 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - accuracy: 0.9455 - auc: 0.9814 - loss: 0.1218 - precision: 0.9726 - recall: 0.9391
Epoch 1: val_loss improved from None to 0.01524, saving model to C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm_parallel\artifacts\kaggle\best_parallel_cnn_lstm.keras

Epoch 1: finished saving model to C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm_parallel\artifacts\kaggle\best_parallel_cnn_lstm.keras
854/854 ━━━━━━━━━━━━━━━━━━━━ 2169s 3s/step - accuracy: 0.9824 - auc: 0.9981 - loss: 0.0476 - precision: 0.9916 - recall: 0.9810 - val_accuracy: 0.9952 - val_auc: 0.9996 - val_loss: 0.0152 - val_precision: 0.9992 - val_recall: 0.9934
Epoch 2/50
854/854 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - accuracy: 0.9955 - auc: 0.9995 - loss: 0.0144 - precision: 0.9979 - recall: 0.9952
Epoch 2: val_loss improved from 0.01524 to 0.01210, saving model to C:\Users\admin\Desktop\obfuscated-web-attack-detection\cnn_lstm_parallel\artifacts\kaggle

KeyboardInterrupt: 

## 7. Nguyên tắc đọc kết quả

- Chỉ so sánh cùng dataset trên đúng test split dùng chung.
- OBFU_HTTP còn có `test_unseen_technique`, `test_unseen_seed` và `test_unseen_both`; các kết quả này được lưu trong metadata để đánh giá khái quát hóa.
- Cả hai model được re-score ở threshold 0.5; Precision, Recall và F1 là của lớp Attack (1).
- Early stopping có thể dừng ở số epoch khác nhau vì đó là cùng một quy tắc áp dụng cho hai topology.
- Số tham số vẫn khác do topology. Bảng phải công bố parameter count; nếu muốn kết luận độc lập hoàn toàn với capacity, cần thêm thí nghiệm parameter-matched và nhiều seed.


## 8. Thống kê cuối notebook

Hai bảng dưới đây ghi lại quy mô, phân bố nhãn, độ dài và test metrics của đúng hai split tham chiếu. Kết quả được lưu trong `cnn_lstm_parallel/artifacts/`.


In [ ]:
split_statistics_rows = []
dataset_statistics_rows = []
trained_results = globals().get("all_results", {})

for dataset_name, splits in dataset_splits.items():
    clean_summary = preprocessing_metadata["datasets"][dataset_name]["clean"]
    total_over_max_len = 0
    dataset_max_len = int(topology_contracts[dataset_name]["max_len"])

    for split_name, frame in splits.items():
        lengths = frame["payload"].str.len()
        label_counts = frame["label"].value_counts().to_dict()
        over_max_len = int((lengths > dataset_max_len).sum())
        total_over_max_len += over_max_len
        split_statistics_rows.append({
            "dataset": dataset_name,
            "split": split_name,
            "rows": int(len(frame)),
            "normal": int(label_counts.get(0, 0)),
            "attack": int(label_counts.get(1, 0)),
            "attack_rate": float(frame["label"].mean()),
            "mean_length": float(lengths.mean()),
            "median_length": float(lengths.median()),
            "p95_length": float(lengths.quantile(0.95)),
            "max_length": int(lengths.max()),
            "over_max_len": over_max_len,
            "over_max_len_rate": float((lengths > dataset_max_len).mean()),
        })

    clean_rows = int(clean_summary["rows"])
    clean_labels = clean_summary["label_counts"]
    overview = {
        "dataset": dataset_name,
        "clean_rows": clean_rows,
        "normal": int(clean_labels.get("0", 0)),
        "attack": int(clean_labels.get("1", 0)),
        "attack_rate": int(clean_labels.get("1", 0)) / clean_rows if clean_rows else 0.0,
        "train_rows": int(len(splits["train"])),
        "validation_rows": int(len(splits["val"])),
        "test_rows": int(len(splits["test"])),
        "p95_length": float(clean_summary["length"]["p95"]),
        "max_length": int(clean_summary["length"]["max"]),
        "max_len": dataset_max_len,
        "over_max_len": total_over_max_len,
        "over_max_len_rate": total_over_max_len / clean_rows if clean_rows else 0.0,
        "test_accuracy": None,
        "test_auc_roc": None,
        "test_attack_recall": None,
        "test_attack_f1": None,
        "test_false_positives": None,
        "test_false_negatives": None,
    }

    if dataset_name in trained_results:
        test_result = trained_results[dataset_name]["evaluation"]["test"]
        attack_report = test_result["classification_report"]["Attack (1)"]
        overview.update({
            "test_accuracy": float(test_result["accuracy"]),
            "test_auc_roc": test_result["auc_roc"],
            "test_attack_recall": float(attack_report["recall"]),
            "test_attack_f1": float(attack_report["f1-score"]),
            "test_false_positives": int(test_result["false_positives"]),
            "test_false_negatives": int(test_result["false_negatives"]),
        })

    dataset_statistics_rows.append(overview)

dataset_statistics = pd.DataFrame(dataset_statistics_rows)
split_statistics = pd.DataFrame(split_statistics_rows)

ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)
dataset_statistics.to_csv(ARTIFACT_ROOT / "dataset_statistics.csv", index=False, encoding="utf-8")
split_statistics.to_csv(ARTIFACT_ROOT / "dataset_split_statistics.csv", index=False, encoding="utf-8")

print("=== TỔNG QUAN TỪNG DATASET ===")
display(dataset_statistics)
print("=== CHI TIẾT TỪNG SPLIT ===")
display(split_statistics)
print("Đã lưu:", ARTIFACT_ROOT / "dataset_statistics.csv")
print("Đã lưu:", ARTIFACT_ROOT / "dataset_split_statistics.csv")


## 9. Biểu đồ kết quả CNN ∥ LSTM song song theo từng dataset

Cell dưới đây chỉ đọc artifact của kiến trúc **CNN ∥ LSTM song song**. Mỗi nhóm trên trục ngang là một dataset; ba cột biểu diễn Precision, Recall và F1-score của lớp `Attack (1)` trên tập test tại ngưỡng mặc định 0.5.


In [ ]:
PLOT_DATASETS = ["kaggle", "csic", "obfu_http"]

import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display

VALID_PLOT_DATASETS = {"kaggle", "csic", "obfu_http"}
unknown_datasets = set(PLOT_DATASETS) - VALID_PLOT_DATASETS
if unknown_datasets:
    raise ValueError(f"Dataset không hợp lệ: {sorted(unknown_datasets)}")


def load_parallel_attack_metrics(dataset_name):
    result_path = ARTIFACT_ROOT / dataset_name / "metadata_and_results.json"
    if not result_path.exists():
        raise FileNotFoundError(
            f"Chưa có artifact CNN ∥ LSTM song song cho dataset {dataset_name!r}: "
            f"{result_path}\nHãy train dataset này bằng notebook rồi chạy lại cell biểu đồ."
        )

    with result_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if payload.get("dataset") != dataset_name:
        raise ValueError(
            f"Artifact {result_path} không khớp dataset: "
            f"metadata={payload.get('dataset')!r}, expected={dataset_name!r}."
        )

    try:
        attack_report = payload["evaluation"]["test"]["classification_report"]["Attack (1)"]
    except KeyError as exc:
        raise KeyError(
            f"Artifact {result_path} thiếu kết quả lớp 'Attack (1)': {exc}"
        ) from exc

    metrics = [
        100.0 * float(attack_report["precision"]),
        100.0 * float(attack_report["recall"]),
        100.0 * float(attack_report["f1-score"]),
    ]
    return metrics, result_path


metric_names = ["Precision", "Recall", "F1-score"]
metric_rows = []
plotted_datasets = []
missing_datasets = []
result_paths = {}

for dataset_name in PLOT_DATASETS:
    try:
        metrics, result_path = load_parallel_attack_metrics(dataset_name)
    except FileNotFoundError:
        missing_datasets.append(dataset_name)
        continue

    metric_rows.append(metrics)
    plotted_datasets.append(dataset_name)
    result_paths[dataset_name] = result_path

if not metric_rows:
    raise FileNotFoundError(
        "Chưa có artifact CNN ∥ LSTM song song cho bất kỳ dataset nào trong "
        f"{PLOT_DATASETS}. Hãy train ít nhất một dataset trước."
    )

if missing_datasets:
    print(
        "Cảnh báo: bỏ qua dataset chưa có artifact:",
        ", ".join(name.upper() for name in missing_datasets),
    )

metric_values = np.asarray(metric_rows, dtype=float)
dataset_labels = [name.upper() for name in plotted_datasets]

metric_table = pd.DataFrame(
    metric_values,
    index=dataset_labels,
    columns=metric_names,
)
metric_table.index.name = "Dataset"
display(metric_table.round(2).style.format("{:.2f}%"))

x = np.arange(len(plotted_datasets))
width = 0.22
colors = ["#5B9BD5", "#ED7D31", "#A5A5A5"]

fig, ax = plt.subplots(figsize=(10, 6))
for metric_index, (metric_name, color) in enumerate(zip(metric_names, colors)):
    offset = (metric_index - 1) * width
    bars = ax.bar(
        x + offset,
        metric_values[:, metric_index],
        width,
        label=metric_name.upper(),
        color=color,
    )
    ax.bar_label(bars, fmt="%.2f", padding=3, fontsize=9)

lowest_metric = float(metric_values.min())
y_min = max(0.0, np.floor((lowest_metric - 5.0) / 5.0) * 5.0)
ax.set_ylim(y_min, 100.5)
ax.set_ylabel("Giá trị (%)")
ax.set_xticks(x)
ax.set_xticklabels(dataset_labels)
ax.set_title("CNN ∥ LSTM SONG SONG TRÊN TỪNG DATASET", fontsize=16, pad=18)
ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.10), ncol=3, frameon=False)
ax.grid(axis="y", alpha=0.30)
ax.set_axisbelow(True)
for spine in ("top", "right"):
    ax.spines[spine].set_visible(False)

fig.tight_layout()
chart_path = ARTIFACT_ROOT / "parallel_metrics_by_dataset.png"
fig.savefig(chart_path, dpi=300, bbox_inches="tight")
plt.show()

for dataset_name, result_path in result_paths.items():
    print(f"{dataset_name.upper():12s}: {result_path}")
print("Đã lưu biểu đồ:", chart_path)
